### ISSUE TITLE
How to download - RZ MPU Codec Library Unrestricted Version V1.0 ?

### ISSUE THREAD

**Issue by iamblue** [Avnet/meta-rzboard#2]
As title.
I found RZ wiki (https://renesas.info/wiki/RZ-G/RZ-G2_BSP), it don't show about Unrestricted Version for RZ/V2L.

**Comment by ljkeller** [comment]
Hi @iamblue 

Supported unrestricted codec libraries can be found at the bottom of this page: https://www.renesas.com/us/en/products/microcontrollers-microprocessors/rz-arm-based-high-end-32-64-bit-mpus/rz-mpu-video-codec-library-evaluation-version-rzv2l . 

Does that answer your question?
