### ISSUE TITLE
glibc undefined reference to `__dso_handle'

### ISSUE THREAD

**Issue by karhan-atom** [Avnet/meta-rzboard#6]
I'm trying to build the rzboard image with Qt enabled, in a Ubuntu 20.04 docker image, and the build is failing at glibc, with the following errors from the build log. 

linux/9.3.0/ld: /Shared/rz_qt5_3.0.4_ubuntu20.04/yocto_rzboard/build/tmp/work/aarch64-poky-linux/glibc/2.31-r0/build-aarch64-poky-linux/libc_nonshared.a(pthread_atfork.oS): in function `__pthread_atfork':
/usr/src/debug/glibc/2.31-r0/glibc-2.31/nptl/pthread_atfork.c:51: undefined reference to `__dso_handle'

Build Configuration:
BB_VERSION           = "1.46.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-20.04"
TARGET_SYS           = "aarch64-poky-linux"
MACHINE              = "rzboard"
DISTRO               = "poky"
DISTRO_VERSION       = "3.1.21"
TUNE_FEATURES        = "aarch64 cortexa55"
TARGET_FPU           = ""
SOC_FAMILY           = "rzv2l:r9a07g054l"

**Comment by karhan-atom** [comment]
@ljkeller

**Comment by ljkeller** [comment]
User resolved this issue by building on a different disk?!

> at last, latest build seems to be successful 😃
> 
> so the trick is to build it on a EXT4 disk instead of an NTFS disk .. moving on to testing the image
