### ISSUE TITLE
RZ/V2L Multi-OS Package link downloads V1.12 instead of V1.10

### ISSUE THREAD

**Issue by akarnil** [Avnet/meta-rzboard#8]
https://www.renesas.com/us/en/document/sws/rzv2l-cm33-multi-os-package-v110?r=1570181

Takes you to https://www.renesas.com/us/en/document/sws/rzv-multi-os-package-v112?r=1570181 now
breaking the `create_yocto_rz_src.sh` script

**Comment by akarnil** [comment]
Used https://www.renesas.com/us/en/document/sws/rzv-multi-os-package-v110 which seems to do the job

**Comment by ljkeller** [comment]
Hi,

I noticed the same issue; I opened up a ticket with Renesas regarding their hosting. They are working on updating their website with hosting dependencies for VLP 3.0.4.

Something went wrong on their end with the Release of VLP 3.0.5; they deleted some of the dependencies for the VLP 3.0.4 release.

If you need Renesas files in a pinch, and you can't find them, don't be afraid to reach out to their technical support: https://en-support.renesas.com/dashboard .
